# Generated by Django 5.2.3 on 2025-07-04 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_category_options_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discourses', to='items.item', verbose_name='Item')),
                ('members', models.ManyToManyField(related_name='discourses', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Discourse',
                'verbose_name_plural': 'Discourses',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscourseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('discourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discourse.discourse', verbose_name='Discourse')),
            ],
            options={
                'verbose_name': 'Discourse Message',
                'verbose_name_plural': 'Discourse Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
